### ISSUE TITLE
useAsyncTask missing from distribution + installing own copy of Composition-Api

### ISSUE THREAD

**Issue by Hawxy** [MartinMalinda/vue-concurrency#21]
`useAsyncTask` was never added to https://github.com/MartinMalinda/vue-concurrency/blob/master/src/index.ts and thus I can't seem to use it in my application.

I'm also running into https://github.com/vuejs/composition-api/issues/372, as vue-concurrency installs beta.10 for itself whilst I'm using beta.14

**Comment by MartinMalinda** [comment]
@Hawxy thanks! I'll add the useAsyncTask and release later today

Regarding https://github.com/vuejs/composition-api/issues/372 last time I checked it was hard to solve but there seems to be new approaches now, I'll investigate

**Comment by MartinMalinda** [comment]
`useAsyncTask` [released in 1.2.1](https://github.com/MartinMalinda/vue-concurrency/commits/master)

**Comment by MartinMalinda** [comment]
I have opened a branch for Vue 3 support here: https://github.com/MartinMalinda/vue-concurrency/pull/22. I'll be doing some changes to bundling there so it might also fix the issue with different composition api versions.

**Comment by MartinMalinda** [comment]
I've just released [2.0.0](https://github.com/MartinMalinda/vue-concurrency/commit/4b24819b63316bd65e9fa826909c769e8f158f86) that should elimiate the @vue/composition-api version issue.

I tested via create-vite-app (vue3) and create-nuxt-app (vue2) and I didn't run into any errors.

**Comment by Hawxy** [comment]
Thanks, I'll test it out as soon as I can.

Looking at the changes, is there a reason you didn't use vue-demi for the dual-version compatibility? That's the go-to I see people using.

**Comment by MartinMalinda** [comment]
I ran into an issue with it: https://github.com/antfu/vue-demi/issues/5, but I used the postinstall trick from it. Basically the same path as [vue-composable](https://github.com/pikax/vue-composable). I can run the test suite both for Vue2 and Vue3.

**Comment by Hawxy** [comment]
Everything appears to be working, thanks for your work!
