### ISSUE TITLE
AbortError is called even though task ended with success status

### ISSUE THREAD

**Issue by JkmAS** [MartinMalinda/vue-concurrency#53]
AbortError is called even though the task ended with `success` status. This happens to me on route change.

Maybe it's related to this issue https://github.com/MartinMalinda/vue-concurrency/issues/13

```js
const task = useTask(function* (signal) {
    const revert = (error?) => {
      console.log('status': task.last?.status); // success
      notifyError();
    };
    signal.pr.catch(revert); // <-- abort('cancel')
    try {
      yield apiTask.perform();
    } catch (e) {
      revert(e);
    }
  }).drop();
```

**Comment by MartinMalinda** [comment]
Fixed in 2.1.3 https://github.com/MartinMalinda/vue-concurrency/commit/76af0d55549d1ca39c0dedfd082af3fab007a907
