### ISSUE TITLE
Question: can use vue-concurrency with android app?

### ISSUE THREAD

**Issue by elfxby** [MartinMalinda/vue-concurrency#74]
I am using capacitor to create an android app. In debug mode everything works, but the release app only gives a white screen.

white screen:
```
const task = useTask(function* () {
  yield timeout(700)
})
```

**Comment by MartinMalinda** [comment]
I don't see a reason why this would break. I'd guess capacitor still use a webview right? So it uses android chrome under the hood. It should have support for generator functions.
