### ISSUE TITLE
Question: is there any migration steps between major versions ?

### ISSUE THREAD

**Issue by Bartheleway** [MartinMalinda/vue-concurrency#94]
I was wondering if migrating from version 2 to 4 was involving any refactoring or what are the breaking changes.
I tried to read through the release notes and didn't clearly found anything.

By the way, thanks for the work !

**Comment by MartinMalinda** [comment]
I don't think so! The main reason for the major version changes are that the newer versions of Vue concurrency no longer support older versions of Vue 2. Version 4 support only Vue 3 and Vue 2.7.Sent from my iPhoneOn 11. 3. 2023, at 11:26, Barthélemy L. ***@***.***> wrote:﻿
I was wondering if migrating from version 2 to 4 was involving any refactoring or what are the breaking changes.
I tried to read through the release notes and didn't clearly found anything.
By the way, thanks for the work !

**Comment by Bartheleway** [comment]
Thanks for your reply, I did upgrade without noticing any failures ;)
